### ISSUE TITLE
external links to phylotrees broken in several senses

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/mine-issues#103]
e.g. https://mines.legumeinfo.org/arachismine/report.do?id=18017579 (note that the "shareable" URL comes up blank for this)
sense 1 in which it is broken is that it seems to be making the gene family id in the generated link: java.lang.IllegalAccessException:%20Couldn't%20get%20field
sense 2 in which it is broken is that these links should point to the new version of the tree display at (e.g.):
https://funnotate.legumeinfo.org/?family=legfed_v1_0.L_8RDHM2

I'm assuming this is the same on all mines, though I have only noticed it working with arachismine.

**Comment by sammyjava** [comment]
1. Shareable URLs hopefully fixed throughout; hadn't kept up with data model changes.
2. GeneFamily.primaryIdentifier now used in link.
3. Link updated to funnotate.

2 and 3 are correct on most mines, just three needed updating:

- [x] aeschynomenemine
- [x] arachismine
- [x] lupinusmine
