### ISSUE TITLE
creating lists from mRNAs triggers error; "transcript" lists work

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/mine-issues#104]
mRNA seem to be the thing returned by some keyword searches(e.g. LysM on VignaMine or CicerMine), while "transcript" is the target of some template queries. It seems a little weird in the first place that mRNAs are getting returned for this query while the corresponding proteins are not- maybe the mRNAs have fastas with descriptive header lines and the proteins do not? In any case, the main issue is that the mRNAs don't seem to be list-able; stack trace below

I found this error on https://mines.legumeinfo.org/vignamine/layout.jsp.

---- Error Found ----

java.lang.RuntimeException: ERROR: AnnotationController query invalid: [Path MRNA.gene.geneFamily.primaryIdentifier in view list is not in the model, Path MRNA.gene.geneFamily.description in view list is not in the model, Path MRNA.gene.geneFamily.primaryIdentifier in order by list is not in the model]at org.ncgr.intermine.web.AnnotationController.execute(AnnotationController.java:125)at org.apache.struts.tiles.actions.TilesAction.execute(TilesAction.java:76)at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:425)at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:228)at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1913)at org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:449)at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:711)at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:578)at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:517)at org.apache.struts.tiles.UrlController.execute(UrlController.java:92)at org.apache.struts.tiles.taglib.InsertTag$InsertHandler.doEndTag(InsertTag.java:879)at org.apache.struts.tiles.taglib.InsertTag.doEndTag(InsertTag.java:465)at org.apache.jsp.bagDisplayers_jsp._jspx_meth_tiles_005finsert_005f0(bagDisplayers_jsp.java:455)at org.apache.jsp.bagDisplayers_jsp._jspx_meth_c_005fif_005f1(bagDisplayers_jsp.java:391)at org.apache.jsp.bagDisplayers_jsp._jspx_meth_c_005fforEach_005f1(bagDisplayers_jsp.java:347)at org.apache.jsp.bagDisplayers_jsp._jspx_meth_c_005fif_005f0(bagDisplayers_jsp.java:310)at org.apache.jsp.bagDisplayers_jsp._jspx_meth_c_005fforEach_005f0(bagDisplayers_jsp.java:270)at org.apache.jsp.bagDisplayers_jsp._jspService(bagDisplayers_jsp.java:159)at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:466)at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:379)at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:327)at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:711)at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:578)at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:517)at org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:994)at org.apache.jasper.runtime.PageContextImpl.include(PageContextImpl.java:485)at jdk.internal.reflect.GeneratedMethodAccessor2496.invoke(Unknown Source)at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.base/java.lang.reflect.Method.invoke(Method.java:568)at org.apache.struts.tiles.TilesUtilImpl.doInclude(TilesUtilImpl.java:129)at org.apache.struts.tiles.TilesUtil.doInclude(TilesUtil.java:152)at org.apache.struts.tiles.taglib.InsertTag.doInclude(InsertTag.java:764)at org.apache.struts.tiles.taglib.InsertTag$InsertHandler.doEndTag(InsertTag.java:896)at org.apache.struts.tiles.taglib.InsertTag.doEndTag(InsertTag.java:465)at org.apache.jsp.bagDetails_jsp._jspx_meth_tiles_005finsert_005f2(bagDetails_jsp.java:2272)at org.apache.jsp.bagDetails_jsp._jspx_meth_c_005fif_005f3(bagDetails_jsp.java:2230)at org.apache.jsp.bagDetails_jsp._jspx_meth_c_005fwhen_005f0(bagDetails_jsp.java:574)at org.apache.jsp.bagDetails_jsp._jspx_meth_c_005fchoose_005f0(bagDetails_jsp.java:391)at org.apache.jsp.bagDetails_jsp._jspService(bagDetails_jsp.java:261)at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:466)at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:379)at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:327)at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:711)at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:578)at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:517)at org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:994)at org.apache.jasper.runtime.PageContextImpl.include(PageContextImpl.java:485)at jdk.internal.reflect.GeneratedMethodAccessor2496.invoke(Unknown Source)at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.base/java.lang.reflect.Method.invoke(Method.java:568)at org.apache.struts.tiles.TilesUtilImpl.doInclude(TilesUtilImpl.java:129)at org.apache.struts.tiles.TilesUtil.doInclude(TilesUtil.java:152)at org.apache.struts.tiles.taglib.InsertTag.doInclude(InsertTag.java:764)at org.apache.struts.tiles.taglib.InsertTag$InsertHandler.doEndTag(InsertTag.java:896)at org.apache.struts.tiles.taglib.InsertTag.doEndTag(InsertTag.java:465)at org.apache.jsp.layout_jsp._jspx_meth_tiles_005fget_005f1(layout_jsp.java:1157)at org.apache.jsp.layout_jsp._jspService(layout_jsp.java:286)at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:466)at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:379)at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:327)at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:711)at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459)at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:385)at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:313)at org.apache.struts.action.RequestProcessor.doForward(RequestProcessor.java:1083)at org.apache.struts.tiles.TilesRequestProcessor.doForward(TilesRequestProcessor.java:295)at org.apache.struts.tiles.TilesRequestProcessor.processTilesDefinition(TilesRequestProcessor.java:271)at org.apache.struts.tiles.TilesRequestProcessor.internalModuleRelativeForward(TilesRequestProcessor.java:370)at org.apache.struts.action.RequestProcessor.processForward(RequestProcessor.java:566)at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:212)at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1913)at org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:449)at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)at org.intermine.web.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:139)at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)at org.intermine.web.filters.PermanentURLFilter.doFilter(PermanentURLFilter.java:62)at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:433)at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789)at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by sammyjava** [comment]
Oddly, I skipped over MRNA when I updated the path queries in AnnotationController to Foo.gene.geneFamilyAssignments. Done.
