### ISSUE TITLE
Phylonodes with numerical "identifier"

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/mine-issues#108]
This is bad. Do something about these records. Maybe don't store identifier. Is this a datastore issue?
```
minimine=> select identifier from phylonode where identifier like '0%';
 identifier 
------------
 0.794
 0.704
 0.998
 0.810
 0.977
```

**Comment by adf-ncgr** [comment]
my guess is that something (a parser) is treating branch lengths on nodes as identifiers. They are typically anonymous but I think the newick standard does technically make allowance for having names and other metadata associated with internal nodes (e.g. if they represent speciation or duplication events). is it causing problems?

**Comment by sammyjava** [comment]
No, I just don't want to store those numbers as identifiers. No biggy, I just have to update the loader.

**Comment by sammyjava** [comment]
This was actually a bug and is now fixed.
