### ISSUE TITLE
List analysis heatmap matrix for gene families

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/mine-issues#112]
per email discussion, we'd like to be able to look at varying counts of gene family memberships across annotation sets, in a manner conceptually similar to how gene expression displays. The pre-computation of membership counts in Tallies will be changed to be on a per-annotation-version basis instead of by Organism as it currently is set. We'll eventually want to do the same thing for PanGenes, which I think are right around the corner. 

I suppose that it's a little different than the gene expression case in that you could (in theory) want to subset the "columns" (ie not show all annotation versions) but we don't have predefined subgroups as is the case with Experiments and their samples. So maybe it's more analogous to the way you were approaching the genotype matrix display, which IIRC did support slicing by both row and column (ie sample subsets and marker subsets). Just something to think about, not sure how critical this is at this point, but I guess in LegumeMine the set of annotations would be already >100 which might make for a cramped display.

thanks for taking it on!

**Comment by sammyjava** [comment]
Pondering this, I realize I do need to update the data model since it currently has 
```
  <!-- tally of genes per GeneFamily per Organism -->                                                                                                                                                              
  <class name="GeneFamilyTally" is-interface="true">                                                                                                                                                               
    <attribute name="tally" type="java.lang.Integer"/>                                                                                                                                                             
    <reference name="geneFamily" referenced-type="GeneFamily" reverse-reference="tallies"/>                                                                                                                        
    <reference name="organism" referenced-type="Organism"/>                                                                                                                                                        
  </class> 
```
So this will be a 5.1.0.3 update, I'll add it to the 5.1.0.3 issue. I'll tally the various groupings: per organism, per strain, per annotation. Let me know if there's any other tally grouping you'd like.

**Comment by adf-ncgr** [comment]
I guess it might be interesting to see things at the genus level, but to be honest I think any grouping above the individual annotation level will run into issues of representation bias (ie having more members in some groups than others). I suppose higher level tallies could be normalized in terms of the number of things in the group- maybe something to consider.

**Comment by sammyjava** [comment]
> I guess it might be interesting to see things at the genus level, but to be honest I think any grouping above the individual annotation level will run into issues of representation bias (ie having more members in some groups than others). I suppose higher level tallies could be normalized in terms of the number of things in the group- maybe something to consider.

I suppose we could store fraction as well as tally for each grouping. Don't see any reason not to, it's just numbers.

**Comment by sammyjava** [comment]
EDITED.
Just to double-check, we're talking about a heat map like this, right? org = species, avgCount is average tally of gene assignments per annotation for that org.

|  | org1 | org2 | org3 | org4 |
| --- | --- | --- | --- | --- |
| **genefam1** |  avgCount11 | avgCount12  | avgCount13 | avgCount14 |
| **genefam2** |  avgCount21 | avgCount22  | avgCount23 | avgCount24 |
| **genefam3** |  avgCount31 | avgCount32  | avgCount33 | avgCount34 |

This is for a gene family list page.

Note the current GeneFamilyTally design in 5.1.0.3 is:
```xml
<class name="GeneFamilyTally" is-interface="true" term="">                                                                                                                                                         
        <attribute name="averageCount" type="java.lang.Double"/>                                                                                                                                                   
        <attribute name="totalCount" type="java.lang.Integer"/>                                                                                                                                                    
        <attribute name="numAnnotations" type="java.lang.Integer"/>                                                                                                                                                
        <reference name="organism" referenced-type="Organism"/>                                                                                                                                                    
        <reference name="geneFamily" referenced-type="GeneFamily" reverse-reference="tallies"/>                                                                                                                    
</class>
```

**Comment by adf-ncgr** [comment]
yep, that's the idea

**Comment by sammyjava** [comment]
This is done and displayed on MiniMine 5.1.0.3, soon to appear on LegumeMine 5.1.0.3.
