### ISSUE TITLE
GlycineMine Template Region -> Gene

### ISSUE THREAD

**Issue by jd-campbell** [legumeinfo/mine-issues#119]
On GlycineMine the Template for Region to Gene state there is no genes for the entire chromosome (I tested Gm01, Gm02, Gm03).  I wonder if the genome version needs to be added to the template. 

![Screen Shot 2023-06-05 at 16 15 33](https://github.com/legumeinfo/mine-issues/assets/13021601/ca8f1c23-449f-4a0c-8907-a2ea141460a2)
![Screen Shot 2023-06-05 at 16 15 52](https://github.com/legumeinfo/mine-issues/assets/13021601/4964bed7-5461-4c84-b7b9-fd1cb798e52c)

**Comment by sammyjava** [comment]
Weird, I don't know why that dropdown got messed up. We have a lot more chromosomes now, 1,094, so it won't do a drop-down, it now provides a text input for the full Chromosome identifier (e.g. glyma.Wm82.gnm2.Gm01). But still odd that it showed the short names, not the full identifiers. Anyway it's fixed, thanks for letting me know!
