### ISSUE TITLE
GlycineMine: Add filter to the the GO Terms -> Genes template

### ISSUE THREAD

**Issue by jd-campbell** [legumeinfo/mine-issues#121]
Please add a genome and annotation filter to the template.

**Comment by sammyjava** [comment]
Done. Would you want a strain filter, though, as well? It's a bit odd to filter on a particular genome/annotation for all strains, methinks.

**Comment by jd-campbell** [comment]
@sammyjava I think that is a good idea. Thank you for your help.

**Comment by sammyjava** [comment]
Done.

**Comment by adf-ncgr** [comment]
@jd-campbell I'm seeing some unusual activity on the database that may be related to the query Sam implemented here. If you are noticing anything odd about the behavior on your end (e.g. taking much longer to get results than expected) please let me know. I may want to disable it temporarily, it may be filling up our temp space on the db server.

**Comment by adf-ncgr** [comment]
I may have jumped to the conclusion that the queries I saw consuming temp space were related to this template query, or they may have been left over from an earlier form of it. In any case, as far as I can tell the template query works just fine.

**Comment by sammyjava** [comment]
I just summarized the template, which ran fast as I watched the pg_stat_activity. And that normally runs quickly. I think it was flailing on pre-computing the template since before I left. So I'll avoid doing that.
