### ISSUE TITLE
Gene-> Transcripts and Sequence on GlycineMine

### ISSUE THREAD

**Issue by maxglycine** [legumeinfo/mine-issues#124]
The example search seems to find nothing.  Did it fail?

**Comment by adf-ncgr** [comment]
Yes, I think the Identifier supplied needs to have "full yuck", e.g. glyma.Wm82.gnm4.ann1.Glyma.01G005400
@sammyjava I don't think I'm a superuser in the mines anymore, otherwise I'd try to fix it (or maybe I've just forgotten where to go to exercise superpower)

**Comment by sammyjava** [comment]
Well, I write the templates to not require full-yuck-knowledge by normal users, but this and other templates need to be updated to match the current data model. Identifier is now Name and primaryIdentifier is now called "Identifier" in the web app. I've updated this template and I'll rifle through all the templates today and fix these issues. I'll close this and make a new super-issue addressing that.
