### ISSUE TITLE
CicerMine issue : json showing 

### ISSUE THREAD

**Issue by jd-campbell** [legumeinfo/mine-issues#129]
I was messing around CicerMine and I found an issue that this location: 
https://mines.legumeinfo.org/cicermine/report.do?id=20812128&trail=%7c20812128
<img width="1025" alt="Screen Shot 2023-09-28 at 09 26 55" src="https://github.com/legumeinfo/mine-issues/assets/13021601/b07e6fb7-be8d-4404-9856-631fe1f57e0b">

**Comment by adf-ncgr** [comment]
Thanks @jd-campbell, good eye. @sammyjava incidentally this seems to indicate that you are handling replicate groups in the mines at least in a basic way- relevant to the peanut data I recently passed your way.

**Comment by sammyjava** [comment]
Thanks, @jd-campbell I had a debug flag set to true. And yes, @adf-ncgr I use color coding to indicate rep groups, I was wondering if I had an option to average into a single bar (bad) which I don't do (good).
