### ISSUE TITLE
mines "launch page": lupinus japonicus is not a thing

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/mine-issues#13]
on https://mines.legumeinfo.org :
LupinMine - Lupinus albus and japonicus => LupinMine - Lupinus albus and angustifolius

on https://mines.legumeinfo.org/lupinmine/begin.do :
White and narrow-leaf lupin (Lupinus angustifolius and japonicus)  => White and narrow-leaf lupin (Lupinus albus and angustifolius)

**Comment by sammyjava** [comment]
Whoa. "Brain fart." Lupin, lotus, name your poison. Remind me why we don't have a lotja mine? Just me not building one?

**Comment by sammyjava** [comment]
OH now I remember - that was supposed to be a collaboration with Saskatchewan. Never happened.

**Comment by sammyjava** [comment]
BirdsfootMine? TrefoilMine? Actually LotusMine sounds best.

**Comment by sammyjava** [comment]
> on https://mines.legumeinfo.org/lupinmine/begin.do :
> White and narrow-leaf lupin (Lupinus angustifolius and japonicus) => White and narrow-leaf lupin (Lupinus albus and angustifolius)

I can't grep this one -- are you looking at a cached mine?
```
[shokin@intermine lupinmine]$ grep -R japonicus
dbmodel/resources/organism_config.properties:taxon.34305.species = japonicus
```

**Comment by StevenCannon-USDA** [comment]
I vote LotusMine.
It would certainly have value, as a model. It's mostly been used in Japan and Europe, but there's been good work done on it.

**Comment by adf-ncgr** [comment]
looking at:
https://mines.legumeinfo.org/lupinmine/begin.do 
I don't think it's cached, but I guess it's possible:
![image](https://user-images.githubusercontent.com/2009605/95781456-13605580-0c8b-11eb-94cd-37dbfc3d7fe2.png)

**Comment by sammyjava** [comment]
Ah, I get it. I had already changed it but hadn't redeployed the mine.
![Screenshot_2020-10-12 LupinMine Home](https://user-images.githubusercontent.com/5657219/95782031-30495880-0c8c-11eb-9e8e-95836afc034f.png)

**Comment by adf-ncgr** [comment]
Regarding LotusMine (which I agree should be a thing, though apparently it already exists and is not too far from where the Manson family hung out): 
this reminds me that we have a "Gifu" accession lotus genome that Europeans had sent us and we set aside due to what seemed to be some weird annotation issues; maybe worth revisiting before hitting LotusMine "in anger"...

**Comment by adf-ncgr** [comment]
looks good. closing...
