### ISSUE TITLE
Stop loading phylotrees?

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/mine-issues#139]
Lately I've been skipping the phylotree loader on MiniMine because we've got a linkout to Funnotate. I'm wondering - is there any reason to store the phylotrees in the mines? Are we actually querying them from the mines? We've got linkouts to the trees in a much more useful display.

"View Funnotate phylogram for family of ..."
![image](https://github.com/legumeinfo/mine-issues/assets/5657219/31c7ee5b-d933-4c73-968b-dd753719941c)

**Comment by sammyjava** [comment]
Also note that the Gene Family report page has a direct attribute link to Funnotate.
![image](https://github.com/legumeinfo/mine-issues/assets/5657219/a7996d4e-cc2b-4ca4-b82e-b9adaf81c375)

**Comment by alancleary** [comment]
Yes. The phylotree web component my summer intern implemented uses it [via GraphQL](https://github.com/legumeinfo/web-components/blob/phylotree/dev/lis-phylotree.html#L66). This hasn't been merged into main yet but I am very much still planning to finish it up and deploy it on the site.

Alan

**Comment by sammyjava** [comment]
AH forgot about that. Then we'll keep them in the mines!

**Comment by adf-ncgr** [comment]
@alancleary can you confirm whether that simply requests the Newick string? If so, it might still be possible for @sammyjava to simplify what he's loading (not parsing the trees into Phylonodes with inter-relations). Maybe that is not a big win, though.

**Comment by sammyjava** [comment]
I can also probably speed up the loader. The Newick text is the bulk of the data since the other two classes are just relations and identifiers.

**Comment by adf-ncgr** [comment]
OK, I'm happy to keep fully parsed trees if you are.

**Comment by sammyjava** [comment]
For sure, just checking on what needs to stay in the garage. :)
