### ISSUE TITLE
Remove port from shareable URI

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/mine-issues#146]
With HTTP proxying on port 8080 the sharable links include the port, e.g.
```
https://mines.legumeinfo.org:8080/glycinemine/gene:glyma.Wm82.gnm2.ann1.Glyma.01G086900
```
Update the shareable links to drop the port. Thanks for the good eye, @adf-ncgr !

**Comment by StevenCannon-USDA** [comment]
Thanks. I also stumbled across that yesterday too.

**Comment by adf-ncgr** [comment]
Great minds link alike ;)

**Comment by adf-ncgr** [comment]
I think this was fixed, closing
