### ISSUE TITLE
Missing chromosome_prefix and supercontig_prefix

### ISSUE THREAD

**Issue by svengato** [legumeinfo/mine-issues#153]
Each genome in the data store must specify these in their README.yml, otherwise the validator will detect it and make the InterMine build fail.

Can there be more than one supercontig_prefix? For the Vicia genomes, it looks like `contig_` and `ptg` are both valid. (To do: rebuild the mine with one or both of these - I had tentatively set it to something else, so no supercontigs get added to the database.)

**Comment by svengato** [comment]
Using `contig` locally on lupini-mines.

**To do:** Remember to change the README and CHANGES files in the data store.

**Comment by adf-ncgr** [comment]
I think the current logic allows you to specify the chromosome_prefix without specifying a supercontig_prefix and anything that does not match the former will be considered a supercontig (allowing some heterogeneity). I'm not in love with this way of doing things, but it's probably workable for most situations.

**Comment by svengato** [comment]
It did expect a supercontig_prefix.

**Comment by adf-ncgr** [comment]
OK, looks like you can supply a comma-delimited list so I guess just do it that way

**Comment by svengato** [comment]
> To do: Remember to change the README and CHANGES files in the data store.

Done.
