### ISSUE TITLE
GlycineMine - shorten search instructions

### ISSUE THREAD

**Issue by StevenCannon-USDA** [legumeinfo/mine-issues#166]
I would like to shorten the instruction text in the GlycineMine home page "Analyze a List" box like so:

```
Enter a <b>list</b> of identifiers, e.g. (Gene):
Glyma.15g026400, Glyma.19g001000
Click <b>advanced</b> for other options.
```

The problem with the current text is that it takes up six lines, which
causes the type selector to be non-functional, and the user can't see what's expected ("Gene" or "Protein") -- so every query ends up going to the "advanced" page.
<img width="645" alt="Screenshot 2024-06-27 at 1 25 29 PM" src="https://github.com/legumeinfo/mine-issues/assets/3588740/81edbb9e-4215-4a90-8086-d4e2db3c85c6">

Also, in all of the mines, we should replace this text in the Welcome box: "Contact Sam Hokin shokin at ncgr dot org."

**Comment by svengato** [comment]
Like this?
https://mines.dev.lis.ncgr.org/glycinemine/begin.do

**Comment by StevenCannon-USDA** [comment]
@svengato -- yes, much better!
Can we use these as the example genes, though:
`Glyma.01G000750, Glyma.01G036125`
These are found in only one annotation set (Wm82.gnm6.ann1), so they get the user more quickly to the gene report page (without going through the intermediate "duplicates were found" page).

**Comment by svengato** [comment]
Changed to `Glyma.01G000750, Glyma.01G036125`.

**Comment by StevenCannon-USDA** [comment]
Thanks, @svengato. Closing this issue.

**Comment by svengato** [comment]
Updated in production as well,
https://mines.legumeinfo.org/glycinemine/begin.do

**Comment by StevenCannon-USDA** [comment]
@svengato Thanks - but weirdly, on production I am seeing the previous symptom that the type selector in the "Analyze a List" box is non-functional. 
Tested with Chrome, Safari, and Firefox, with MacOS, on a laptop -- so conceivably the browser window size could be a factor; however, it works fine on the dev instance, where the dropdown shows Gene / Pathway / QTL / Protein.
Among all of the mines, I see this problem only for GlycineMine.

**Comment by svengato** [comment]
I see it too, I suspect that is a separate issue but will look into it.

**Comment by adf-ncgr** [comment]
not %100 sure but I think this may be something a superuser configures through the web interface. At least so I infer from 
`                "im:preferredBagType", null, "class", im.getProfileManager().getSuperuser());`
in intermine/webapp/src/main/java/org/intermine/web/struts/BeginAction.java
I already have superuser status in glycinemine so can have a look

**Comment by adf-ncgr** [comment]
OK, I've figured out how to do this, and have done it in glycinemine (using Gene and Protein which is what LegumeMine used and seemed sensible). How to do it is definitely non-intuitive, but shouldn't need to be redone since this metadata is stored in the userprofile database. Let me know if further issues/questions

**Comment by adf-ncgr** [comment]
For the record, hints on how to effect this given here:
http://intermine.org/im-docs/docs/webapp/query-builder/index/

**Comment by StevenCannon-USDA** [comment]
Thanks, @adf-ncgr and @svengato .
