### ISSUE TITLE
Change BAR eFP link

### ISSUE THREAD

**Issue by maxglycine** [legumeinfo/mine-issues#178]
BAR eFP link on the right panel of the GlycineMine gene report in the "LIS Linkouts" section 

![Screenshot 2024-10-28 at 1 27 09 PM](https://github.com/user-attachments/assets/4ae3d49a-4888-4208-833d-4be54bd6abc9)

needs to be changed to:

https://bar.utoronto.ca/efpsoybean/cgi-bin/efpWeb.cgi?dataSource=soybean&mode=Absolute&primaryGene=Glyma.12G040000&searchSubmit=GO
@adf-ncgr , @StevenCannon-USDA , @jd-campbell

**Comment by adf-ncgr** [comment]
I can change it, but curious as to why that's the preferred target; or maybe we should offer both? Seems like there are more datasets in the one you've proposed, but possible more functionality in the tool of the one that's currently linked. I don't have strong feelings about it, I just had the impression that the ePlant viewer was BAR's preferred (non-legacy) way of presenting the data. But the fact that some experiments don't appear to be accessible there is definitely non-ideal.

**Comment by maxglycine** [comment]
Andrew:

As, Steven will attest, that URL allows you to see all the datasets.  There iare clickable links near the top of the page that will bring up the different "views".
![Screenshot 2024-10-28 at 3 22 50 PM](https://github.com/user-attachments/assets/4762c5d7-da4c-4478-9ca9-eaa0683331ac)
@adf-ncgr @StevenCannon-USDA @jd-campbell

**Comment by adf-ncgr** [comment]
OK, I've changed it for now. I'll note that in the ePlant viewer you can switch to Experiment & Tissue View by clicking on the microscope icon, but it seems like the only other dataset you currently get access to for soybean is the Severin et al. atlas. Presumably at some point the others will be added, but it might take some squeaking to make it happen. In any case I'll close this for now, but feel free to reopen if I didn't get it the way you wanted.
