### ISSUE TITLE
BLAST link is broken

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/mine-issues#18]
So fix it.

**Comment by adf-ncgr** [comment]
could consider being "forward-looking" and try linking to the SequenceServer implementation that Nathan put into place; not sure this is a good idea, but pretty sure it is an idea.

**Comment by sammyjava** [comment]
Actually I think we already decided to do so, or at least use a more modern LIS BLAST service than just fill-in-the-form. Isn't there a new LIS BLAST service in the works, or is that just another name for SequenceServer now?

**Comment by adf-ncgr** [comment]
Umm, this is what I was thinking of:
https://legumeinfo.org/sequenceserver/

**Comment by sammyjava** [comment]
Sounds good, will do.

**Comment by sammyjava** [comment]
Astonishingly, there seems to be no way to fill the query sequence form with a POST or GET. I've pored over the code on GitHub and they seem to only support an API that requires you to poll job completion and then pull the results, which I don't want to do. I just want to prefill the form with a sequence. Looking at search.js, it seems like they mean to support it with a URL like
```
https://legumeinfo.org/sequenceserver/?query=ATCATCATCGTGT
```
but it doesn't work. Do you know differently, @nathanweeks ??? I'm flabbergasted that they don't supply a method for prefilling the form programatically.

**Comment by sammyjava** [comment]
OK, I take it back, I figured it out after perusing the issues and also just looking at the form that gets generated. Here's a handy example that works and BLASTs against some phavu databases on the example NCGR SequenceServer:
```
    <form id="blast" method="post" action="http://dev.lis.ncgr.org:50030/">

      <div style="margin:10px">
        SEQUENCE:<br/>
        <textarea id="sequence" name="sequence" placeholder="Paste query sequence(s) in FASTA format here..." style="width:1000px;height:50px"></textarea>
      </div>

      <div style="margin:10px">
        ADVANCED PARAMETERS:<br/>
        <input type="text" size="100" id="advanced" name="advanced" value="" placeholder="eg: -evalue 1.0e-5 -num_alignments 100" title="View, and enter advanced parameters."/>
      </div>

      <h4>Nucleotide databases</h4>
      <div style="margin:10px">
        <input type="checkbox" name="databases[]" value="95f639d57dc589e10203de7f3789cab7"  data-reactid=".0.1.0.2.$DB_nucleotide.0.1.$DB_nucleotide18.0.0">
        <span data-reactid=".0.1.0.2.$DB_nucleotide.0.1.$DB_nucleotide18.0.1"> phavu G19833.gnm1.ann1.pScz transcript primaryTranscript</span><br/>
        <input type="checkbox" name="databases[]" value="d63811b3af225591e3e900781ba7ad6f"  data-reactid=".0.1.0.2.$DB_nucleotide.0.1.$DB_nucleotide19.0.0">
        <span data-reactid=".0.1.0.2.$DB_nucleotide.0.1.$DB_nucleotide19.0.1"> phavu G19833.gnm1.zBnF genome main</span><br/>
        <input type="checkbox" name="databases[]" value="b05f440b54f7a81344f75d564209a800"  data-reactid=".0.1.0.2.$DB_nucleotide.0.1.$DB_nucleotide20.0.0">
        <span data-reactid=".0.1.0.2.$DB_nucleotide.0.1.$DB_nucleotide20.0.1"> phavu G19833.gnm2.ann1.PB8d transcript primaryTranscript</span><br/>
        <input type="checkbox" name="databases[]" value="4cea1233a0a6406af6fdc1aa10e96e4b"  data-reactid=".0.1.0.2.$DB_nucleotide.0.1.$DB_nucleotide21.0.0">
        <span data-reactid=".0.1.0.2.$DB_nucleotide.0.1.$DB_nucleotide21.0.1"> phavu G19833.gnm2.fC0g genome main</span><br/>
        <input type="checkbox" name="databases[]" value="478c81fb849f8b542b00d64688d36e82"  data-reactid=".0.1.0.2.$DB_nucleotide.0.1.$DB_nucleotide22.0.0">
        <span data-reactid=".0.1.0.2.$DB_nucleotide.0.1.$DB_nucleotide22.0.1"> phavu UI111.gnm1.3VTM genome main</span><br/>
      </div>

      <div style="margin:10px">
        <input type="submit" id="method" name="method" value="blastn"/>
      </div>

    </form>
```

**Comment by sammyjava** [comment]
You can query the databases with a URL like:
```
http://dev.lis.ncgr.org:50030/searchdata.json
```
or
```
https://legumeinfo.org/sequenceserver/searchdata.json
```

**Comment by adf-ncgr** [comment]
great, sounds like a winner! thanks for sorting it out

**Comment by sammyjava** [comment]
I'd still like to just pre-fill the sequence on the SequenceServer and have the user take it from there. Posted an issue.
https://github.com/wurmlab/sequenceserver/issues/491

**Comment by sammyjava** [comment]
Replaced with new SequenceServer BLAST form-button.
