### ISSUE TITLE
google sign in option broken on all (probably) production mines

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/mine-issues#22]
per my email:

looks like the OAuth stuff on the production mines is perhaps in a dysfunctional state.
There's an unexpected (to me) "Test OAuth2 WS" button/textbox and the sign in with google option gives:
Authorization Error
Error 401: deleted_client
The OAuth client was deleted.

**Comment by sammyjava** [comment]
Credentials were deleted, presumably after the 100-day trial period. Authorizing the domain requires a large amount of work which is simply not worth it. Google sign-in will be removed.
