### ISSUE TITLE
Add size attribute to GeneFamily

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/mine-issues#23]
a nice-to-have for someday; possibly other summary statistics could be useful, e.g. avg/max/min length of assigned proteins. anything like this we add to gene family representations would also be nice-to-haves for pangene-sets.

**Comment by sammyjava** [comment]
Hacking the keyword search overview for specific object type functionality is out of scope. I can certainly add a displayer on the GeneFamily report page. Reopen if that's what you meant rather than keyword search results.

**Comment by adf-ncgr** [comment]
I guess I'm not clear on how the set of attributes displayed on search results are determined. I was imagining that just as sequence features get lengths displayed, gene families could get sizes displayed (assuming we were to make that an explicit attribute of gene families, which would have to be updated when new annotations were loaded). I agree it's not worth hacking, I just thought these behaviors were configurable via properties files.

**Comment by sammyjava** [comment]
OK so let's make this a more fundamental issue: add size attribute to GeneFamily. Downstream uses of that attribute can be addressed later. Reopening for that specific task.

**Comment by sammyjava** [comment]
Note to self: this is a post-processor since the members are added from each GFA load. Meaning size = number of genes in THIS mine in this gene family. (We no longer load the genes from LEGUMES/Fabaceae/genefamilies/ due to inconsistencies with the GFA assignments.)

**Comment by sammyjava** [comment]
- [x] add GeneFamily.size
- [ ] create lis-populate-genefamily-sizes

**Comment by sammyjava** [comment]
This is done, and the sizes are actually updated in the direct-updates script with a simple SQL update. Perhaps writing a post-processor for this simple task would be a good homework exercise.
