### ISSUE TITLE
vigan.Gyeongwon proteins not have sequences in cowpeamine

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/mine-issues#24]
example: 
https://mines.legumeinfo.org/cowpeamine/protein:Vang07g05040.1

There are also some cowpea accessions that appear to have similar issues but I think I managed to determine that in their case it was due to gene family assignment files that were lacking full yuck in the protein column, which does not seem to be the case with vigan.Gyeongwon (AFAICT). See table of proteins for https://mines.legumeinfo.org/cowpeamine/genefamily:legfed_v1_0.L_N38GLP 
where three members have no protein lengths defined (two of which are clearly lacking their yuck).

Anyway, I have updated all of the Vigna gfa files to use the score-based assignment and have tried to correct the issues I saw, but can't seem to figure out what the issue was with vigan.Gyeongwon 

not urgent that this get reloaded, probably I should spend some quality time with CowpeaMine and see if I can find other issues before you bother with a redo.

**Comment by sammyjava** [comment]
Yes, please do. As for Gyeongwon proteins, it looks like the loader crashed, there are hardly any records from that load:
```
cowpeamine=> select * from tracker where sourcename ='vigan.Gyeongwon.gnm3.ann1.3Nz5.protein.faa';
 objectid |  fieldname   |                 sourcename                 | version 
----------+--------------+--------------------------------------------+---------
 17000003 | taxonId      | vigan.Gyeongwon.gnm3.ann1.3Nz5.protein.faa |     229
 17000006 | identifier   | vigan.Gyeongwon.gnm3.ann1.3Nz5.protein.faa |     229
 17000006 | organism     | vigan.Gyeongwon.gnm3.ann1.3Nz5.protein.faa |     229
  9000001 | name         | vigan.Gyeongwon.gnm3.ann1.3Nz5.protein.faa |     229
  9000001 | description  | vigan.Gyeongwon.gnm3.ann1.3Nz5.protein.faa |     229
  9000001 | url          | vigan.Gyeongwon.gnm3.ann1.3Nz5.protein.faa |     229
 76000004 | licence      | vigan.Gyeongwon.gnm3.ann1.3Nz5.protein.faa |     229
 76000004 | publication  | vigan.Gyeongwon.gnm3.ann1.3Nz5.protein.faa |     229
 76000004 | name         | vigan.Gyeongwon.gnm3.ann1.3Nz5.protein.faa |     229
 76000004 | description  | vigan.Gyeongwon.gnm3.ann1.3Nz5.protein.faa |     229
 76000004 | dataSource   | vigan.Gyeongwon.gnm3.ann1.3Nz5.protein.faa |     229
 76000004 | version      | vigan.Gyeongwon.gnm3.ann1.3Nz5.protein.faa |     229
 76000004 | url          | vigan.Gyeongwon.gnm3.ann1.3Nz5.protein.faa |     229
 75004532 | volume       | vigan.Gyeongwon.gnm3.ann1.3Nz5.protein.faa |     229
 75004532 | journal      | vigan.Gyeongwon.gnm3.ann1.3Nz5.protein.faa |     229
 75004532 | pages        | vigan.Gyeongwon.gnm3.ann1.3Nz5.protein.faa |     229
 75004532 | issue        | vigan.Gyeongwon.gnm3.ann1.3Nz5.protein.faa |     229
 75004532 | month        | vigan.Gyeongwon.gnm3.ann1.3Nz5.protein.faa |     229
 75004532 | year         | vigan.Gyeongwon.gnm3.ann1.3Nz5.protein.faa |     229
 75004532 | abstractText | vigan.Gyeongwon.gnm3.ann1.3Nz5.protein.faa |     229
 75004532 | title        | vigan.Gyeongwon.gnm3.ann1.3Nz5.protein.faa |     229
 75004532 | pubMedId     | vigan.Gyeongwon.gnm3.ann1.3Nz5.protein.faa |     229
 75004532 | doi          | vigan.Gyeongwon.gnm3.ann1.3Nz5.protein.faa |     229
 75004532 | firstAuthor  | vigan.Gyeongwon.gnm3.ann1.3Nz5.protein.faa |     229
(24 rows)
```

**Comment by sammyjava** [comment]
So I'll close this in the future when that FASTA gets loaded properly.

**Comment by adf-ncgr** [comment]
OK, FWIW I was browsing datastore-issues and wonder if the issue legumeinfo/datastore-issues#1 that I boldly declared as wontfix and closed could possibly be related to crashing of the loader?

**Comment by sammyjava** [comment]
Oh, this was dumb, I had the wrong filename in for the protein FASTA so only the README got read. But no exception thrown. I've fixed project.xml and tested that the proteins load fine.
