### ISSUE TITLE
External Links for CicerMine

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/mine-issues#27]
please provide links for genes to:
http://dev.lis.ncgr.org:50018/embed/interact/?target=<gene_id>
and for gene families to:
https://legumeinfo.org/chado_phylotree/<gene_family_id>

**Comment by sammyjava** [comment]
Done. External links use attributes and Gene.geneFamily is a reference, so you have to go to the Gene Family report to see the external link for the phylogram.
