### ISSUE TITLE
Faceted filtering by organism not working

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/mine-issues#29]
it appears to filter on things that have organisms but not on the actual value of the organism selected

**Comment by sammyjava** [comment]
This appears to be a core IM bug. I don't think it works on any mine. If you know of a mine where it does work, let me know so I can figure out what's different. It appears to be broken in 4.* as well as 5.0.2.

**Comment by adf-ncgr** [comment]
This may be a clue. I tried it on legumemine and selected Vigna unguiculata as the organism for restriction. The filtering seemed to apply to all Vigna (ie I got a list that excluded everything but Vigna unguiculata, Vigna radiata and Vigna angularis)

**Comment by sammyjava** [comment]
Ahh, thanks. I think I may be doing a core IM fix on this one. I'll see if I can dig it out.

**Comment by adf-ncgr** [comment]
seems like it's basically ignoring stuff after the space in the organism short name (as you will have no doubt divined from the earlier clue)

**Comment by adf-ncgr** [comment]
seemingly having to do with the way SOLR queries need to have things with spaces quoted?
https://sitecore.stackexchange.com/questions/1625/how-to-query-solr-with-spaces-and-slashes-in-the-filters

**Comment by adf-ncgr** [comment]
my guess is  intermine/api/src/main/java/org/intermine/api/searchengine/solr/SolrKeywordSearchHandler.java
line 303

**Comment by sammyjava** [comment]
Good call! Fixed. I'll PR the fix to the core code.
