### ISSUE TITLE
links from heatmap expression displayer in ChickpeaMine are not strain-sensitive

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/mine-issues#31]
because chickpea is a species where gene names can collide without full yuck, we get things like:
https://mines.legumeinfo.org/chickpeamine/portal.do?class=Gene&externalids=Ca_06975

when clicking on the heatmap for a gene labelled Ca_06975 and representing a single one of these (guess which)

**Comment by sammyjava** [comment]
ChickpeaMine is running a highly-outdated version of the heatMap. CowpeaMine is running the current version, which doesn't currently link genes. But when it does, I'll use full yuck and the normal "share" link syntax.
