### ISSUE TITLE
list display broken on peanutmine

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/mine-issues#32]
looks like the same error you fixed on cicermine ( #28 ). An actual user emailed about this one. I'll file an issue too.

I found this error on https://mines.legumeinfo.org/peanutmine/layout.jsp.

---- Error Found ----

java.lang.RuntimeException: Sources query invalid: [Path ExpressionValue.sample.source.id in view list is not in the model, Path ExpressionValue.sample.source.primaryIdentifier in view list is not in the model, Path ExpressionValue.feature in constraint is not in the model, Path ExpressionValue.sample.source.primaryIdentifier in order by list is not in the model]at org.ncgr.intermine.web.HeatMapController.querySources(HeatMapController.java:307)at org.ncgr.intermine.web.HeatMapController.execute(HeatMapController.java:99)at org.apache.struts.tiles.actions.TilesAction.execute(TilesAction.java:76)at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:425)at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:228)at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1913)at org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:449)at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)at

**Comment by sammyjava** [comment]
Yup, fixed. I let him/her know.
