### ISSUE TITLE
bug or feature? all cowpea data returned by keywords "root" and "soils" and "tropics"

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/mine-issues#33]
my guess is that this is because the description for the Organism contains these terms. I stumbled across this trying to do a  perhaps stupid but well-intentioned search for genes with "root" in their descriptors (for expression heat map purposes)

**Comment by sammyjava** [comment]
Yeah BioEntity objects will show on searches that return their organism. I can turn that off.
```
index.references.BioEntity = synonyms organism crossReferences
```

**Comment by adf-ncgr** [comment]
Probably a good idea to turn it off- likely most Mines don't wax quite as eloquent about their species as we do...

**Comment by sammyjava** [comment]
Fixed, I'll update the other mine configs as well.
