### ISSUE TITLE
medicmine: broken at the front page

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/mine-issues#34]
Unable to find the class count.<i>cannot find class count for: org.intermine.model.bio.ProteinHmmMatch</i>

**Comment by sammyjava** [comment]
Argh it's caught in an objectstore summary conflict with the new version. I'll bump rebuilding it under 5.0.2 and the new DS layout. Can't get it to work with the mix of IM version and existing data.

**Comment by adf-ncgr** [comment]
seems to be fixed.
