### ISSUE TITLE
MedicMine: behavior of example gene list wrt expression heatmap

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/mine-issues#35]
Now that visitors to the old mtgea site are being directed to us, I've already received a couple of inquiries- very glad to be able to point them to MedicMine (as well as the French site). One thing I noticed was that the example gene list provided on https://mines.legumeinfo.org/medicmine/bag.do 
does not seem to render an expression heatmap, although one of the genes in the list (Medtr4g113520) does have expression data. I also tried a list of 2 genes both of which have expression barcharts on their report pages (Medtr6g017260 and Medtr4g075040) and again no heatmap displayed on the list page. Unclear to me what the conditions for heatmap display are, but in any case it would be nice to have an example list that would show off this functionality.

**Comment by adf-ncgr** [comment]
PS. this would seemingly be a good "learning moment" so I've tagged it as a good first issue in hopes that either @svengato or myself can at least help fix it.

**Comment by sammyjava** [comment]
I don't see any im:public lists. What example gene list are you referring to? Just the three genes that are stuffed into the form on the home page?

In any case, I've got two Google users on the mine plus me, and Google login is disabled. So once you and/or Sven create an account I can flag you as superadmin so you can tag lists as im:public (which I think we found works, as opposed to tagging the home page template tags, which only I can do).

**Comment by sammyjava** [comment]
Those examples in the forms on the home page are set in web.properties so that's something you should leave until I'm gone and Sven takes over. I'm still tweaking the production mines (or will be when fisher and VMs are back up). You have to redeploy the mine to update those, and that stuff is carried over via the GitHub repos.

**Comment by adf-ncgr** [comment]
yes, I was just talking about the three genes stuffed into the form; also trying to understand why some gene sets don't display the heatmap when it seems they could. But I've created an account so you can anoint me whenever convenient

**Comment by sammyjava** [comment]
Duly anointed.

What do you mean by "it seems they could"? Give me a list of such genes and I'll see if there's a bug in the query. Put it in a separate issue, though, since this issue is about the examples on the home page form.

**Comment by adf-ncgr** [comment]
see #36

**Comment by sammyjava** [comment]
This seems ancient enough to be deleted. I'm not sure there's any actual issue here any longer.
