### ISSUE TITLE
LegumeMine needs definition of which genomes to load

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/mine-issues#37]
We've got a lot of genomes. LegumeMine holds genomes and annotations, while we put genetic data and other stuff in the individual genera mines. However, I don't think it's helpful to have every single genome+annotation in the datastore in LegumeMine. Here is the list of current datastore annotation collections and I've checked the ones I think should go into LegumeMine, generally being the most recent assembly/annotation of the most oft-assembled strain.

- [x] Aeschynomene/evenia/annotations/CIAT22838.gnm1.ann1.ZM3R
- [ ] Arabidopsis/thaliana/annotations/Col.gnm9.ann10.WZQD
- [x] Arachis/duranensis/annotations/V14167.gnm1.ann1.cxSM
- [ ] Arachis/hypogaea/annotations/Tifrunner.gnm1.ann1.CCJH
- [x] Arachis/hypogaea/annotations/Tifrunner.gnm2.ann1.4K0L
- [x] Arachis/ipaensis/annotations/K30076.gnm1.ann1.J37m
- [x] Cajanus/cajan/annotations/ICPL87119.gnm1.ann1.Y27M
- [ ] Cercis/canadensis/annotations/ISC453364.gnm1.ann1.HZJM
- [ ] Chamaecrista/fasciculata/annotations/MN87.gnm1.ann1.LWFM
- [x] Cicer/arietinum/annotations/CDCFrontier.gnm1.ann1.nRhs
- [x] Cicer/arietinum/annotations/ICC4958.gnm2.ann1.LCVX
- [ ] Cucumis/sativus/annotations/Gy14.gnm1.ann1.Y8XX
- [ ] Faidherbia/albida/annotations/unk.gnm1.ann1.RTP9
- [ ] Glycine/max/annotations/FiskebyIII.gnm1.ann1.SS25
- [ ] Glycine/max/annotations/Hefeng25_IGA1002.gnm1.ann1.320V
- [ ] Glycine/max/annotations/Huaxia3_IGA1007.gnm1.ann1.LKC7
- [ ] Glycine/max/annotations/Jinyuan_IGA1006.gnm1.ann1.2NNX
- [ ] Glycine/max/annotations/Lee.gnm1.ann1.6NZV
- [ ] Glycine/max/annotations/Wenfeng7_IGA1001.gnm1.ann1.ZK5W
- [ ] Glycine/max/annotations/Wm82.gnm1.ann1.DvBy
- [ ] Glycine/max/annotations/Wm82.gnm2.ann1.RVB6
- [ ] Glycine/max/annotations/Wm82.gnm2.ann2.BG1Q
- [x] Glycine/max/annotations/Wm82.gnm4.ann1.T8TQ
- [ ] Glycine/max/annotations/Wm82_IGA1008.gnm1.ann1.FGN6
- [ ] Glycine/max/annotations/Zh13.gnm1.ann1.8VV3
- [x] Glycine/max/annotations/Zh13.gnm2.ann1.FJ3G
- [ ] Glycine/max/annotations/Zh13_IGA1005.gnm1.ann1.87Z5
- [ ] Glycine/max/annotations/Zh35_IGA1004.gnm1.ann1.RGN6
- [ ] Glycine/soja/annotations/F_IGA1003.gnm1.ann1.G61B
- [ ] Glycine/soja/annotations/PI483463.gnm1.ann1.3Q3Q
- [x] Glycine/soja/annotations/W05.gnm1.ann1.T47J
- [x] Lotus/japonicus/annotations/MG20.gnm3.ann1.WF9B
- [x] Lupinus/albus/annotations/Amiga.gnm1.ann1.3GKS
- [x] Lupinus/angustifolius/annotations/Tanjil.gnm1.ann1.nnV9
- [x] Medicago/sativa/annotations/XinJiangDaYe.gnm1.ann1.RKB9
- [x] Medicago/truncatula/annotations/A17_HM341.gnm4.ann2.G3ZY
- [ ] Medicago/truncatula/annotations/HM004.gnm1.ann1.2XTB
- [ ] Medicago/truncatula/annotations/HM010.gnm1.ann1.WV9J
- [ ] Medicago/truncatula/annotations/HM022.gnm1.ann1.6C8N
- [ ] Medicago/truncatula/annotations/HM023.gnm1.ann1.WZN8
- [ ] Medicago/truncatula/annotations/HM034.gnm1.ann1.YR6S
- [ ] Medicago/truncatula/annotations/HM050.gnm1.ann1.GWRX
- [ ] Medicago/truncatula/annotations/HM056.gnm1.ann1.CHP6
- [ ] Medicago/truncatula/annotations/HM058.gnm1.ann1.LXPZ
- [ ] Medicago/truncatula/annotations/HM060.gnm1.ann1.H41P
- [ ] Medicago/truncatula/annotations/HM095.gnm1.ann1.55W4
- [ ] Medicago/truncatula/annotations/HM125.gnm1.ann1.KY5W
- [ ] Medicago/truncatula/annotations/HM129.gnm1.ann1.7FTD
- [ ] Medicago/truncatula/annotations/HM185.gnm1.ann1.GB3D
- [ ] Medicago/truncatula/annotations/HM324.gnm1.ann1.SQH2
- [x] Medicago/truncatula/annotations/R108_HM340.gnm1.ann1.85YW
- [x] Medicago/truncatula/annotations/jemalong_A17.gnm5.ann1_6.L2RX
- [x] Phaseolus/lunatus/annotations/G27455.gnm1.ann1.JD7C
- [ ] Phaseolus/vulgaris/annotations/G19833.gnm1.ann1.pScz
- [x] Phaseolus/vulgaris/annotations/G19833.gnm2.ann1.PB8d
- [ ] Phaseolus/vulgaris/annotations/UI111.gnm1.ann1.8L4N
- [x] Pisum/sativum/annotations/Cameor.gnm1.ann1.7SZR
- [ ] Prunus/persica/annotations/Lovell.gnm2.ann1.S2ZZ
- [ ] Solanum/lycopersicum/annotations/Heinz1706.gnm2_5.ann2_4.Q2DC
- [x] Trifolium/pratense/annotations/MilvusB.gnm2.ann1.DFgp
- [x] Vigna/angularis/annotations/Gyeongwon.gnm3.ann1.3Nz5
- [ ] Vigna/angularis/annotations/Shumari.gnm1.ann1.8BRS
- [x] Vigna/radiata/annotations/VC1973A.gnm6.ann1.M1Qs
- [ ] Vigna/unguiculata/annotations/CB5-2.gnm1.ann1.0GKC
- [ ] Vigna/unguiculata/annotations/IT97K-499-35.gnm1.ann1.zb5D
- [x] Vigna/unguiculata/annotations/IT97K-499-35.gnm1.ann2.FD7K
- [ ] Vigna/unguiculata/annotations/Sanzi.gnm1.ann1.HFH8
- [ ] Vigna/unguiculata/annotations/Suvita2.gnm1.ann1.1PF6
- [ ] Vigna/unguiculata/annotations/TZ30.gnm1.ann2.59NL
- [ ] Vigna/unguiculata/annotations/UCR779.gnm1.ann1.VF6G
- [ ] Vigna/unguiculata/annotations/Xiabao_II.gnm1.ann1.4JFL
- [ ] Vigna/unguiculata/annotations/ZN016.gnm1.ann2.C7YV
- [ ] Vitis/vinifera/annotations/PN40024.gnm12X.ann1.V31M

**Comment by sammyjava** [comment]
Another point here is that LegumeMine should be, I think, a fully populated matrix of strains vs. content. So, for example, expression data would not go in LegumeMine since we don't have expression data for many strains. Expression data is loaded in the genus-specific mine. The common content across the board is genomes and annotations.

**Comment by adf-ncgr** [comment]
I'm not sure we don't want to load all genomes with annotations, but I checked a few more in your list that I'd include if we are keeping it to the popular kids. One argument for including all genomes with annotations is that it makes it possible to do one-stop-shopping for use cases like: take all the genes in a region in GCV and get their functional descriptors.
(GCV doesn't believe in cliquishness when it comes to importing genomes, and it would be nice for it to have a single endpoint to communicate with)

**Comment by sammyjava** [comment]
I'll load the checked ones for now and you can take this further down the line when some actual imjs webapps begin to appear and folks are pining for Wenfeng7_IGA1001.

**Comment by sammyjava** [comment]
Closing this since LegumeMine is built for this round.
