### ISSUE TITLE
chickpea mine strains need some cleanup

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/mine-issues#41]
there may or may not be a good reason why non-cicer strains are present, but surely the duplication of cicer strains is a bad thing:

chickpeamine=# select identifier from strain;
       identifier
------------------------
 CDC Frontier
 ICC 4958
 A17_HM341
 MilvusB
 MG20
 ICC4958 (desi variety)
 ICC4958
 CDCFrontier
(8 rows)

**Comment by sammyjava** [comment]
This is solved by the new loaders that read strain identifiers from the description files (which hopefully match those used on the collection identifiers). In other words, the Datastore is getting more self-consistent. If a collection has a non-matching strain in its identifier then that strain will be created, but I've tried to keep an eye out for that.
