### ISSUE TITLE
Descriptions not loaded from FASTAs!

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/mine-issues#46]
This is a surprise to me, I though they were!

**Comment by sammyjava** [comment]
Since we've got type=value in some FASTA headers, implement this as a "descriptionOnly" flag in project.xml for FASTAs of the `>ID Description` variety.

**Comment by adf-ncgr** [comment]
I've actually been wondering about whether we (LIS) ought to consider more standardization of the fasta headers. It seems that proteomics users are befuddled when the protein fastas don't try to make function more explicit without forcing them to get into gff-ese. Perhaps worth some group discussion.
