### ISSUE TITLE
We need a prod-sequenceserver for the prod mines

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/mine-issues#47]
I've got a dev-sequenceserver set up for dev fun, and we should have a stable production sequenceserver for general BLASTing. Which genomes should we put on that? LIS has a lot of genomes, it seems like we should limit the list somewhat. Or, every genome that's in the production mines could be the answer. You decide.

**Comment by adf-ncgr** [comment]
My inclination would be to put in all latest versions of genomes and their annotations (ie transcript and protein files). Which I think would be more or less equivalent to the answer "every genome that's in the production mines" (in theory anyway). This could then serve as an alt-form of friendliness between the mines (ie blast a sequence in one mine to get to things in other mines). No doubt, the list will be a bit large, but I'd rather cause people a little work in selecting targets than to prevent them from having access to some that may be relevant to their work.

**Comment by StevenCannon-USDA** [comment]
I have misgivings about including all of the Data Store's assemblies and annotations into one ss instance. The current count is 85 assemblies and 79 annotations. Maybe that's OK; people would just need to do some scrolling and/or searching.

A somewhat more elaborate solution to consider: use representative genomes and per-genus pan-gene set at the "legume" level, and provide all genomes and CDS/protein sets as targets at the genus level.
That's approximately what we have now (representatives in LIS, most Glycine genomes at SoyBase):
https://legumeinfo.org/sequenceserver/
https://soybase.org/sequenceserver/
... except that the current Glycine sequenceserver collection is already quite selective. We currently have 26 Glycine genomes in the Data Store.

**Comment by sammyjava** [comment]
Not all the Data Stores' assemblies and annotations; all of those in the mines, which are not all of those in the DS. (For example, right now I cannot include multiple genome versions which have the same short names for the genes, like G19833.gnm1.ann1.pScz and G19833.gnm2.ann1.PB8d, because of merging on short name that I need to do with other data sources).

Perhaps a good choice is the genome/annotations in LegumeMine. There's a reason we choose those, and then we can link out to LegumeMine on all the results. Right now LegumeMine contains 23 annotations, namely:
```
CIAT22838.gnm1.ann1.ZM3R
V14167.gnm1.ann1.cxSM
K30076.gnm1.ann1.J37m
ICPL87119.gnm1.ann1.Y27M
CDCFrontier.gnm1.ann1.nRhs
ICC4958.gnm2.ann1.LCVX
Wm82.gnm4.ann1.T8TQ
Zh13.gnm2.ann1.FJ3G
W05.gnm1.ann1.T47J
MG20.gnm3.ann1.WF9B
Amiga.gnm1.ann1.3GKS
Tanjil.gnm1.ann1.nnV9
A17_HM341.gnm4.ann2.G3ZY
R108_HM340.gnm1.ann1.85YW
jemalong_A17.gnm5.ann1_6.L2RX
XinJiangDaYe.gnm1.ann1.RKB9
G19833.gnm2.ann1.PB8d
G27455.gnm1.ann1.JD7C
Cameor.gnm1.ann1.7SZR
MilvusB.gnm2.ann1.DFgp
Gyeongwon.gnm3.ann1.3Nz5
VC1973A.gnm6.ann1.M1Qs
IT97K-499-35.gnm1.ann2.FD7K
```
**I'll start with these** and then you two can argue about adding more.

**Comment by adf-ncgr** [comment]
that seems as good a place to start as any to me, thanks. We will of course be adding more genomes to legumemine eventually...

**Comment by StevenCannon-USDA** [comment]
Agree. Moving forward is good.
