### ISSUE TITLE
Enable Google-based authentication

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/mine-issues#5]
Starting with peanutmine to make @jd-campbell happy, but should propagate to other mines eventually. It works at https://bar.utoronto.ca/thalemine/begin.do

**Comment by sammyjava** [comment]
This is in the works. I made the mistake (?) of supplying a logo for the Google auth screen which it turns out forces the auth screen to be reviewed and validated by Google, because I guess the logo could be NSFW or Amazon or something. Could take weeks. But I've tested it up to the error message that Google returns, so I think it's OK. It's supported by IM, just some properties to set and do the configuring on the Google side.

**Comment by adf-ncgr** [comment]
> forces the auth screen to be reviewed and validated by Google, because I guess the logo could be NSFW or Amazon or something. Could take weeks

surely they would use deep learning to do this more or less automagically? I'm pretty sure they'd have plenty of data available to train the NSFW-CNN on... I wonder if getting a machine to be offended by something is part of the advanced Turing Exams...

**Comment by sammyjava** [comment]
Google validated the OAuth2 consent screen. Now it looks like core IM uses a deprecated API from Google+ which is no longer enable-able. I think I can update the core IM code to use the new API pretty easily, it's well documented.

**Comment by sammyjava** [comment]
Thanks to @danielabutano this is now implemented on all the production mines.
