### ISSUE TITLE
Add Funnotate sequence POST button

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/mine-issues#52]
@adf-ncgr  sez:
Now that https://funnotate.legumeinfo.org/ is live, it would be great to start adding the functionality for POSTing sequences to the production mines. I think it is a code change that would be applicable to any of the mines in their current state of data-tude, but let me know if you think otherwise. Sven, let us know if I've misconstrued the readiness-for-primetime of this feature.
@svengato

**Comment by sammyjava** [comment]
I'll add it to the dev mines, it's still a ways off before those reach production. I've been doing BeanMine lately since it's a lot smaller than SoyMine, but still README work pending on that. It'll be on the new prod mines, tho.

**Comment by svengato** [comment]
It should work with no changes to Funnotate required (only the mines).

**Comment by sammyjava** [comment]
So I remember to add to the dev mines:
- **beanmine**
- [x] web.properties
- [x] webconfig-model.xml
- [x] tiles-defs-model.xml
- [x] struts-config-model.xml
- **chickpeamine**
- [x] web.properties
- [x] webconfig-model.xml
- [x] tiles-defs-model.xml
- [x] struts-config-model.xml
- **cowpeamine**
- [x] web.properties
- [x] webconfig-model.xml
- [x] tiles-defs-model.xml
- [x] struts-config-model.xml
- **jointvetchmine**
- [x] web.properties
- [x] webconfig-model.xml
- [x] tiles-defs-model.xml
- [x] struts-config-model.xml
 - **lupinmine**
- [x] web.properties
- [x] webconfig-model.xml
- [x] tiles-defs-model.xml
- [x] struts-config-model.xml
- **medicmine**
-  [x] web.properties
-  [x] webconfig-model.xml
- [x] tiles-defs-model.xml
- [x] struts-config-model.xml
- **peanutmine**
- [x] web.properties
- [x] webconfig-model.xml
- [x] tiles-defs-model.xml
- [x] struts-config-model.xml
- **soymine**
- [x] web.properties
- [x] webconfig-model.xml
- [x] tiles-defs-model.xml
- [x] struts-config-model.xml
- **legumemine**
- [x] web.properties
- [x] webconfig-model.xml
- [x] tiles-defs-model.xml
- [x] struts-config-model.xml
- **cicermine**
- [x] web.properties
- [x] webconfig-model.xml
- [x] tiles-defs-model.xml
- [x] struts-config-model.xml

**Comment by sammyjava** [comment]
Along with this issue is the "annotation" widget for transcript or protein lists that we talked about today, which I just found:
https://github.com/legumeinfo/mine-webapp/blob/main/model/annotation.jsp
This requires adding the widget to the webconfig along with the URL in web.properties that activates the button on the report pages. @adf-ncgr @svengato So I'll make an effort to do that as I roll out mines, starting with the almost-built new CowpeaMine. And I'll go ahead with SoyMine at least, a recent build. (I'm leery of redeploying the older prod mines due to versionitis that existed before I adopted the exact gradle versioning of the data model that I'm using now.)

**Comment by sammyjava** [comment]
OK, upon further review, this is in fact already present on the production SoyMine and I'll double-check that it's present on any upcoming mines.
![Screenshot 2022-05-23 at 14-57-41 SoyMine List Analysis Proteins from three gene families](https://user-images.githubusercontent.com/5657219/169905433-bc567209-879b-4bd0-a6b0-d4a0ada6ee13.png)

**Comment by adf-ncgr** [comment]
great, thanks! it is indeed working like a charm there on SoyMine, sounds like it's only a matter of time for it to appear in CowpeaMine and others.

**Comment by sammyjava** [comment]
I did totally forget about it. As you can see in the updated tasks above there are three separate things one has to do to activate it on the list analysis page for mRNA, CDS, and Protein. But this was an active issue so "forgetting about it" is probably more accurately "passively ignoring it."

**Comment by adf-ncgr** [comment]
I think production medicmine is almost but not quite right. seemingly due to the action for the form being an empty string:
`<form action="" method="post" style="display:inline;border:0;margin:0;padding:0;" target="_blank">
` 
maybe you are just checking things off in dev now?

**Comment by sammyjava** [comment]
Correct, just hitting things in dev, so they'll be enabled when those mines get promoted. I'm starting a fresh build of MedicMine today on the 5.0.7.1 version. CowpeaMine is grinding post-processing.

**Comment by adf-ncgr** [comment]
There seems to be some issue with cowpea mine and protein lists. I am able to create a list of proteins but in the list analysis page, nothing really seems to be getting populated (in particular, the option to POST sequences to funnotate gets no bootton to press, but it seems the issue is more fundamental since really nothing is displayed)

<img width="1036" alt="image" src="https://user-images.githubusercontent.com/2009605/179552097-c6366b2e-f829-4a97-af58-22ed38cac9d3.png">

Doing the same thing for transcripts, I get typical elements of the list analysis page populated, but the POST bootins are not offered to me. I thought this was a thing, but maybe I'm misremembering.

**Comment by sammyjava** [comment]
Definitely broken, I'll track it down.
```
18-Jul-2022 10:25:28.459 SEVERE [ajp-nio-0.0.0.0-8009-exec-11] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [action] in context with path [/cowpeamine] threw exception [An exception occurred processing [layout.jsp] at line [93]

90:       <tiles:insert page="/contextHelp.jsp"/>
91: 
92:       <tiles:get name="body"/>
93: 
94: <script type="text/javascript">
95: jQuery(document).ready(function() {
96:   jQuery("p#contactUsLink").toggle();


Stacktrace:] with root cause
        java.lang.NullPointerException
```

**Comment by sammyjava** [comment]
It's working on MiniMine so I think I'll just bump CowpeaMine to 5.0.7.3 rather than fix an old version. It's not a big mine, loads pretty fast.

**Comment by sammyjava** [comment]
Hrm my checklist above didn't have struts-config-model.xml on it so I'm off the hook! :)

**Comment by sammyjava** [comment]
OK I'm closing this since I've done the thing on all of the dev mines, the next prod versions should have Funnotatibility.
