### ISSUE TITLE
cowpea mine (and maybe others) not emailing forgotten password requests

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/mine-issues#53]
Unable to send email. Please try again.

**Comment by sammyjava** [comment]
Well I f*cked up CowpeaMine because I'm between versions (which I've now addressed with gradle sub-versions but hadn't pushed to production yet). So now I'll have to rebuild CowpeaMine under 5.0.6.1 and then debug it. I'll do a quick build. Presumably something happened with SMTP on our network but I need to see the actual exception rather than the blurb that InterMine spits out.

**Comment by adf-ncgr** [comment]
yes, it's probably SMTP because I checked and found it is not specific to CowpeaMine. But, FYI I am hoping to use CowpeaMine soon, so let me know when you think it should be working correctly (I needed to log in to make a big list- apparently there's a limit on the size of lists for unauthenticated users)

**Comment by sammyjava** [comment]
I'll get it rebuild. But let me know what you need so I prioritize those collections.

**Comment by adf-ncgr** [comment]
The annotated genome data is what I need, thanks.

**Comment by sammyjava** [comment]
@adf-ncgr do me a favor and sort vigan.Gyeongwon.gnm3.ann1.3Nz5.gene_models_main.gff3 . I probably did so in my previous life but it didn't make it up to the DS. Meanwhile I'm whacking other DS moles.

**Comment by adf-ncgr** [comment]
OK, give it another try and let me know if still not suitable

**Comment by sammyjava** [comment]
Not yet:
```
Caused by: java.lang.RuntimeException: Parent vigan.Gyeongwon.gnm3.ann1.Vang0010ss00020.1,vigan.Gyeongwon.gnm3.ann1.Vang0010ss00020.2 not loaded before child vigan.Gyeongwon.gnm3.ann1.Vang0010ss00020.1:exon:16254. Is the GFF sorted?
```

**Comment by adf-ncgr** [comment]
looks to me like the problem here is that the file uses a legal but regrettable gff3 convention that the parser may not be equipped to handle. vigan.Gyeongwon.gnm3.ann1.Vang0010ss00020.1:exon:16254 is used in two isoforms and expresses that by using gff comma-delimited multi-attributes in the parent field. I believe the individual mRNA to which it refers both do appear before it in the file, and likely the parser is just treating is as a single parent with a comma as part of the identifier it seeks in what came before. We've had bad issues resulting from multi-parent features in the past and I suspect we probably ought to disallow them. That said, I don't have a scripted solution to do so at the moment. It's fine with me to ignore this one for now.

**Comment by sammyjava** [comment]
OK, will ignore.

**Comment by sammyjava** [comment]
Well, it's way worse. We don't have READMEs for all but one vigun genome+annotation collection:
```
[shokin@lis ~/v2/Vigna/unguiculata/annotations]$ ls
CB5-2.gnm1.ann1.0GKC        IT97K-499-35.gnm1.ann2.FD7K Suvita2.gnm1.ann1.1PF6      UCR779.gnm1.ann1.VF6G       ZN016.gnm1.ann2.C7YV
IT97K-499-35.gnm1.ann1.zb5D Sanzi.gnm1.ann1.HFH8        TZ30.gnm1.ann2.59NL         Xiabao_II.gnm1.ann1.4JFL
[shokin@lis ~/v2/Vigna/unguiculata/annotations]$ ls */README.*
IT97K-499-35.gnm1.ann1.zb5D/README.IT97K-499-35.gnm1.ann1.zb5D.yml
[shokin@lis ~/v2/Vigna/unguiculata/annotations]$ 
```
Same for genomes. So to build the new mine I need those READMES. I think I can get away with stubs for now but this is a major DS deficiency. I'll create stubs with the minimal contents.

This slows the process down. Sorry I tried to fix this original issue, I should stay away from production issues when I've advanced the code on dev (although like I said I'm now using specific gradle versions below the IM versions so I can rebuild on the production side by specifying an exact sub-version).

**Comment by adf-ncgr** [comment]
OK, I think that's probably something I was supposed to be doing so let me know if you'd rather punt it my way. It will have to be minimal for now anyway since this is all pre-publication (except for Xiaobao_II which could be excluded for present purposes).

**Comment by sammyjava** [comment]
Nah it's no problem, I'm doing them one at a time while the loader loads the collections, so it's actually not much of a time-slower.

**Comment by sammyjava** [comment]
This is fixed. For reasons I don't recall, hardy's postfix was default, and the firewall didn't have port 25 open. I guess this dates back to when I installed CentOS 8 Stream (!). This means that any servers that used lis.ncgr.org as the SMTP relay were not working. The idea behind that was that we'd not have to run a postfix on every server that sends mail, but we'd use a single LIS machine for that work. Which now works again after several postfix main.cf tweaks. I've got all the genomes on production CowpeaMine, running post-processing and I'll add the genetic data back in, they all have READMEs.

**Comment by sammyjava** [comment]
Sorry, Xiabao_II to come as well, not sure why that was lacking before. (I'm loading directly into the production mine.)

**Comment by StevenCannon-USDA** [comment]
have been tempted to remove Xiabao_II altogether. The annotation is laughably bad. I am not sure about the quality of the assembly. The reason for keeping it is that the biology for this accession is interesting (it is yard-long bean; ssp. sesquipedialis), and there are some decent-looking papers on trait mapping, e.g. https://doi.org/10.3389/fpls.2017.01544
