### ISSUE TITLE
Merge GeneFamily and PhyloTree by GeneFamily.name

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/mine-issues#54]
Which doesn't exist in the 5.0.6.1 data model so do this in the next data model update. (Right now the legfed_v1_0 prefix is hardcoded in the phylotree loader.)

**Comment by sammyjava** [comment]
Dang, missed this in 5.0.6.2.

**Comment by adf-ncgr** [comment]
I think I just ran into this when messing around with GraphQL against legumemine. There are a bunch of GeneFamilies returned without Genes, but these see to be associated with phylotrees, e.g. https://mines.legumeinfo.org/legumemine/report.do?id=265000002
I recently had @svengato switch Funnotate to use full yuck gene families, which might solve this issue as well (or at least remove the need for hardcoding in phylotree loader). Should we go ahead and declare the yuckified gene families (including family name prefixing and member protein prefixing) to be the correct form (by officially replacing old content with this form in the datastore)?

**Comment by sammyjava** [comment]
Well I've already done it in 5.0.6.4. If the DS phylotrees get full yuck I'll need to do another update. But merging on name is fine, I've now got GeneFamily.name and Phylotree.name holding the shorter name.

**Comment by sammyjava** [comment]
And it's not really "yuck" in the sense of normal gensp.strain.gnm[.ann]... in any case, it's just a version prefix. I'm happy with it as it is, but it'll be a while before all the production mines are on 5.0.6.4.

**Comment by sammyjava** [comment]
This was done in 5.0.7.1.
