### ISSUE TITLE
gff loader needs to URL-decode a few things

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/mine-issues#56]
there are a handful of characters that have special meaning in field 9 of GFF and are supposed to be URL-encoded to escape them when appearing in text:

> A list of feature attributes in the format tag=value. Multiple tag=value pairs are separated by semicolons. URL escaping rules are used for tags or values containing the following characters: ",=;". Spaces are allowed in this field, but tabs must be replaced with the %09 URL escape. Attribute values do not need to be and should not be quoted. The quotes should be included as part of the value by parsers and not stripped.

seems like the mine parser is not handling them specially and they are coming through in all their encoded glory in the description (Note attribute); see, e.g. https://mines.legumeinfo.org/legumemine/gene:tripr.MilvusB.gnm2.ann1.gene15995

**Comment by sammyjava** [comment]
Fixed in https://github.com/legumeinfo/lis-bio-sources/commit/220ba6d1c37d251d732e5d1924d69ec4a47ebd93 and will appear in future builds.
