### ISSUE TITLE
production beanmine header logo image being sourced from http://dev.lis.ncgr.org:50030/assets/img/lis-logo-small.png

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/mine-issues#57]
hence broken under https.

**Comment by sammyjava** [comment]
Oh yeah that snuck in, cowpeamine as well, which is on 5.0.6.1 now. I updated it for the near-future URL, which will return a 404 for now, which I'm fine with. Mucks up the header slightly but we WILL be launching the new site on Monday so it's only for a few days! Right?!?

**Comment by adf-ncgr** [comment]
Right!
