### ISSUE TITLE
List length of 100k is just too small for CERTAIN users

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/mine-issues#59]
A certain user reports:

The noncore gene list has ~52k members and loads OK. the core gene list has ~150k members and gives me the message that the list size limit is 100k. I wonder if that's configurable somewhere? If I do this as an anonymous user I get the message:
```
You need to be logged in to save a list with more than 99,999 elements
```
then if I log in I'm told:
```
List has too many elements, maximum size 100,000
```
That seems a little silly, so I'm hoping it can be bumped up easily, but I didn't find anything from a quick google. Not the end of the world if we can't make it so, just let me know if you have any insights.

**Comment by sammyjava** [comment]
It's not a list size limit per se, here's an anonymous list I created with a query with 195k genes. So it's the List Upload...
![image](https://user-images.githubusercontent.com/5657219/172704635-59b4a53f-883f-4b4f-9933-386068fa4e50.png)

**Comment by sammyjava** [comment]
It's set in global.web.properties at 100,000 for logged in and 99,999 for not logged in. That is overridden in web.properties. What should I set it to and on which mine for you to test it? `max.bag.size` and `max.bag.size.notloggedin`

**Comment by sammyjava** [comment]
I can test it on a more recent prod mine (not LegumeMine) that I'm confident I can rebuild due to gradle versioning. Or just sit tight for the new LegumeMine, I'll just bump it to 200,000 there.

**Comment by adf-ncgr** [comment]
OK, FWIW the mine I had wanted it on was CowpeaMine but I don't think it's a pressing issue for cowpeas at this point so whatever is most convenient for you is fine for me.

**Comment by sammyjava** [comment]
That's 5.0.7.1 so duly updated, please confirm that it worked. I left not-logged-in at 99999 so you need to log in. Which you want to do anyway so you save your big list.

**Comment by adf-ncgr** [comment]
a certain user has confirmed that it is working as expected on his list of ~143k genes.
