### ISSUE TITLE
5.0.7.2 TO-DOs

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/mine-issues#65]
- [x] GenotypingSample = Annotatable + description, name, organism, strain, dataSet
- [x] handle gzipped FASTAs and GFFs and TSVs (so I don't have to gunzip them from DS)
- - [x] lis-annotation
- - [x] lis-expression
- - [x] lis-fasta
- - [x] lis-genetic
- - [x] lis-map
- - [x] lis-markers
- - [x] lis-mstmap
- - [x] lis-synteny
- [x] add Gene<->ProteinDomain reverse reference as per @adf-ncgr 
- [x] new GeneFamilyAssignment with Gene.geneFamilyAssignments, Protein.geneFamilyAssignments to support multiple gene family assignments per gene/protein
```xml
  <!-- stores a gene family assignment along with various measures -->
  <class name="GeneFamilyAssignment" is-interface="true">
    <attribute name="eValue" type="java.lang.Double"/>
    <attribute name="score" type="java.lang.Double"/>
    <attribute name="bestDomainScore" type="java.lang.Double"/>
    <reference name="geneFamily" referenced-type="GeneFamily"/>
  </class>
```
- [x] lis-annotation: associate protein with gene via transcript.ID=protein.ID rather than [gene.ID].n as per @adf-ncgr 
- [x] lis-annotation: same deal with CDS (also loaded from a FASTA)

**Comment by sammyjava** [comment]
@adf-ncgr can I rely on the protein-named transcript being type=mRNA in the GFF? Or do I have to drill through other transcripty types?

**Comment by adf-ncgr** [comment]
I think you can rely on it (as much as anything else in gffland, anyway).

**Comment by sammyjava** [comment]
**Collatoral Damage**
- [x] SequenceAnnotateUtil
- [x] funnotate buttons - HACK: limit to gene family identifiers that start with "legfed" (whatever that is)
- [x] gene family enrichment widget - in webconfig so EACH MINE
- [x] funnotate list analysis widget - same HACK

**Comment by sammyjava** [comment]
In production as of https://github.com/legumeinfo/intermine/commit/891971b501ca450e11b2a9ca763ecf4b90534dc9
