### ISSUE TITLE
5.0.7.3 TO-DOs

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/mine-issues#67]
- [x] -Phylotree.name, +Phylotree.identifier - merge on identifier
- [x] -Phylonode.name, +Phylonode.identifier = phylotree identifier.number
- [x] -Newick.name, +Newick.identifier
- [x] -GeneFamily.name, +GeneFamily.identifier - merge on identifier
- [x] ProteinDomain extends Annotatable rather than BioEntity
- [x] prefix ProteinMatch and ProteinHmmMatch identifiers with gensp.strain.gnm.ann for unique primaryIdentifier
- [x] ProteinHmmMatch extends ProteinMatch; Protein.proteinMatches reverse references ProteinMatch.proteins
- [x] GeneFamilySpeciesTally .organism .tally

**Comment by sammyjava** [comment]
@adf-ncgr let me know if you think of anything else as I"m going to go ahead with these for MiniMine and then LegumeMine. Pretty minor.

**Comment by sammyjava** [comment]
Note: had to modify interpro loader because it defined ProteinDomain as BioEntity. Probably precedes the introduction of Annotatable.

**Comment by sammyjava** [comment]
@adf-ncgr tell me what you think: https://dev.lis.ncgr.org/minimine/begin.do

**Comment by sammyjava** [comment]
@adf-ncgr you have any problem with this? I got collisions loading LegumeMine because so many iprscan records have the same identifiers, by chance. Didn't catch it on MiniMine since I only had one iprscan file. I've been standardizing to unique primaryIdentifier within a class rather than using multiple keys. (I'm fine with prepending the yuck in this case, it's one line and the match IDs are arbitrary, anyway.)
```
minimine-dev=> select primaryidentifier,secondaryidentifier from proteinmatch limit 5;
                primaryidentifier                | secondaryidentifier 
-------------------------------------------------+---------------------
 cicar.CDCFrontier.gnm2.ann1.match$71983_118_219 | match$71983_118_219
 cicar.CDCFrontier.gnm2.ann1.match$11914_28_299  | match$11914_28_299
 cicar.CDCFrontier.gnm2.ann1.match$159351_55_212 | match$159351_55_212
 cicar.CDCFrontier.gnm2.ann1.match$38874_287_297 | match$38874_287_297
 cicar.CDCFrontier.gnm2.ann1.match$52829_43_161  | match$52829_43_161
(5 rows)

minimine-dev=> select primaryidentifier,secondaryidentifier from proteinhmmmatch limit 5;
                 primaryidentifier                 |  secondaryidentifier  
---------------------------------------------------+-----------------------
 cicar.CDCFrontier.gnm2.ann1.match$96116_558_628   | match$96116_558_628
 cicar.CDCFrontier.gnm2.ann1.match$100026_35_165   | match$100026_35_165
 cicar.CDCFrontier.gnm2.ann1.match$94243_1216_1276 | match$94243_1216_1276
 cicar.CDCFrontier.gnm2.ann1.match$43065_20_289    | match$43065_20_289
 cicar.CDCFrontier.gnm2.ann1.match$12485_23_485    | match$12485_23_485
(5 rows)
```

**Comment by adf-ncgr** [comment]
sorry, I got distracted from checking out minimine, but sounds like you're now asking if full yuck on iprscan records is OK? Seems reasonable to do so, I think I had done something to make sure the IDs were unique within a given file but had not thought about collisions between files. You can assign me the task of fixing existing files (and the process of generating them) if this is indeed what we're talking about now.

**Comment by sammyjava** [comment]
No, ***do nothing***. I just wanted to check that you're OK with me prepending the yuck. Let's keep the iprscan files just as they are; those IDs are totally arbitrary anyway and don't really deserve LIS decoration in the datastore IMO.

**Comment by sammyjava** [comment]
And this is in a new MiniMine build, will be done soon.

**Comment by adf-ncgr** [comment]
OK, sounds good; nothing doing is generally my favorite way to contribute.

**Comment by sammyjava** [comment]
Do you want Protein.proteinMatches to include HMM matches or have separate Protein.proteinHmmMatches? Typically it's not better to split things if they're similar (and they are).

**Comment by sammyjava** [comment]
The idea behind that is that I'll just have ProteinHmmMatch extend ProteinMatch and Protein.proteinMatches includes both by inheritance. I think that's how I had it way back.

**Comment by sammyjava** [comment]
+create-genefamilytally post-processor populates GeneFamily.size and creates GeneFamilyTally objects. Man, I'm rusty on post-processors, spent way too much time struggling with something I used to know. But got it in the end.

**Comment by sammyjava** [comment]
![image](https://user-images.githubusercontent.com/5657219/174669454-4fdb9d24-55e3-4ea2-b7fd-4f05305b9fe2.png)

**Comment by sammyjava** [comment]
I think I'll go ahead and promote MiniMine unless you have more recommendations for 5.0.7.3. I'd like to get chunking on LegumeMine before I vanish to the Old Country.

**Comment by adf-ncgr** [comment]
chunk away!
