### ISSUE TITLE
production soymine is missing dataset: G1134.gnm1.ann1.4BJM

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/mine-issues#68]
from Glycine/dolichocarpa, although it has the corresponding genome G1134.gnm1.PP7B

not sure if this means the gff had an issue or it just somehow got overlooked (but it's in the project.xml so probably not the latter). Anyway, perennial glycine fans can probably wait until @sammyjava is back

**Comment by sammyjava** [comment]
Added.

**Comment by sammyjava** [comment]
Yeah I musta missed that it bombed in the scroll. Easy to add in once it's 
fixed.
