### ISSUE TITLE
MedicMine: not able to create list of things annotated by GO Term (annotatables)

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/mine-issues#70]
from https://mines.legumeinfo.org/medicmine/goterm:GO:0048364
I tried to create a list of the Ontology Annotations' Subjects (in this case, the elements are mostly mRNA features although I saw later that some ProteinDomains also appear), but when trying to create the list am given the error message:
 Error Service failed. Please contact support.

so I am contacting you, support me when convenient (no time sensitivity on this). I'll note that on the theory that the mixed types of having mRNA and ProteinDomains was causing trouble, I tried filtering out the Protein Domains but it didn't help. It's possible that my filtering strategy (CONTAINS medtr) did not do what I intended as it seemed that rows were not actually removed although the IPR accessions that appeared in the first column got replaced with a grey "NO" as shown below
<img width="1180" alt="image" src="https://user-images.githubusercontent.com/2009605/179323778-f9d99c2a-de67-4c06-a1bb-76aefd84efcb.png">

**Comment by sammyjava** [comment]
This query 500's but runs fine in query builder:
```
<query model="genomic" view="GOTerm.ontologyAnnotations.subject.id" ><join path="GOTerm.ontologyAnnotations.subject" style="OUTER"/><constraint path="GOTerm.id" op="=" value="31477758" code="A" /></query>
```

POST https://mines.legumeinfo.org/medicmine/service/query/tolist
[HTTP/1.1 500 500 111ms]

executionTime	"2022.08.10 08:44::43"
wasSuccessful	false
error	"Service failed. Please contact support."
statusCode	500

**Comment by sammyjava** [comment]
From the command line:
```#!/bin/sh
URL=http://localhost:8080/medicmine/service/query/tolist
QUERY='<query model="genomic" view="GOTerm.ontologyAnnotations.subject.id"><join path="GOTerm.ontologyAnnotations.subject" style="OUTER"/><constraint path="GOTerm.id" op="=" value="31477758" code="A"/></query>'
curl -v --data-urlencode "$QUERY" $URL
```
returns a 401 auth error, not 500, but still fails:
```
*   Trying ::1:8080...
* Connected to localhost (::1) port 8080 (#0)
> POST /medicmine/service/query/tolist HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.76.1
> Accept: */*
> Content-Length: 284
> Content-Type: application/x-www-form-urlencoded
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 
< Set-Cookie: JSESSIONID=5C4B7FED9A1418F9A85C50E0058D8FF1; Path=/
< Access-Control-Expose-Headers: Content-Encoding, Content-Type, Content-Length, Content-Range
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: DELETE, POST, GET, OPTIONS, PUT
< Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Range, Authorization, Content-Length, Content-Range
< Content-Disposition: attachment; filename="result.json"
< Pragma: no-cache
< Cache-Control: must-revalidate, max-age=0
< Content-Type: application/json;charset=UTF-8
< Transfer-Encoding: chunked
< Date: Wed, 10 Aug 2022 14:50:54 GMT
< 
{
* Connection #0 to host localhost left intact
"executionTime":"2022.08.10 08:50::54","wasSuccessful":false,"error":"This service requires authentication.","statusCode":401}
```

**Comment by sammyjava** [comment]
I think this is a serious core bug in IM. Still the case in 5.0.8.1 LegumeMine.

**Comment by sammyjava** [comment]
GAH I can't test it on legacy FlyMine because they don't show the Ontology Annotations on a GO Term page. :( I want to throw this one at Daniela.

@danielabutano have you come across this bug? Attempting to create a list of subjects from a table of ontology annotations on a GO Term report errors out on /service/query/tolist while the query itself runs fine from the query builder. Running it from the command line returns a 401 authentication error. But doesn't matter whether you're logged in or not.

**Comment by sammyjava** [comment]
So I'm gonna close this since it's something pretty deep in the core and I definitely don't want to deal with it.

One can always get the subjects (which in this case are mRNAs, not genes) with a path query.
```
<query name="" model="genomic" view="OntologyAnnotation.subject.primaryIdentifier" longDescription="" sortOrder="OntologyAnnotation.subject.primaryIdentifier asc">
  <constraint path="OntologyAnnotation.ontologyTerm.identifier" op="=" value="GO:0048364"/>
  <constraint path="OntologyAnnotation.subject" type="MRNA"/>
</query>
```
