### ISSUE TITLE
choice of type for upload list identifiers should probably always default to Gene

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/mine-issues#73]
for example https://mines.legumeinfo.org/cowpeamine/begin.do gives "Expression Sample" as the default type (which the unsuspecting user may not think to change).

**Comment by sammyjava** [comment]
So, those are the im:preferredBagType tagged objects which I tag for appearance on top of the query builder selector. But I agree that we should probably "go genomic" with those and just have Gene + Protein, which being alphabetical has Gene appearing first. If there is something else that comes after Gene alphabetically, feel free to suggest. I'll update those on all the mines right now, it's just a tagging exercise.
