### ISSUE TITLE
XinJiangDaYe.gnm1.ann1.RKB9 genes loaded without descriptions

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/mine-issues#76]
datastore version looks OK to me, so not sure why they would be empty in the mine itself.

**Comment by sammyjava** [comment]
Very weird. I'll rebuild it and look at that load carefully.

**Comment by sammyjava** [comment]
Well, for utterly mysterious reasons the descriptions loaded fine in a re-build. I have no idea what happened. It's a long load, still running, but I'll refresh 'er when done, probably Friday with the long post-process.

**Comment by adf-ncgr** [comment]
OK, thanks; the ways of the mines are mysterious, but they maketh the faithful to rejoice

**Comment by sammyjava** [comment]
5.0.8.1 public now, has descriptions.

**Comment by adf-ncgr** [comment]
thanks! came in just as I was discussing gene content of XinJiangDaYe with our USDA collaborator on alfalfa genomics.
