### ISSUE TITLE
latest build of MedicMine does not include the MtGEA expression data

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/mine-issues#80]
probably because this was done as a one-off and was never represented in the datastore proper. But, I just had a user asking about the MtGEA data which made me realize the omission. Luckily, I can point interested parties to the MtExpress site for their immediate needs, but it would be good to restore this important dataset- we could certainly discuss making it a real citizen of the datastore if it would help stabilize its inclusion in the builds (and it might be a good idea anyway)

**Comment by adf-ncgr** [comment]
actually, looks like you already had put this data in the datastore:
/Medicago/truncatula/expression/A17_HM341.gnm4.ann2.expr.He_Vagner_2009/README.A17_HM341.gnm4.ann2.expr.He_Vagner_2009.yml
so, I guess you just forgot about loading it...

**Comment by sammyjava** [comment]
Added. (But still keyword reindexing.)
