### ISSUE TITLE
cowpea mine expression display small issues

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/mine-issues#82]
- [x] bar chart bars when moused over are giving unhelpful descriptions ("SRRxxx : undefined"); the heat map is a little better in this regard
- [x] heat map genes are not linking properly to the gene report pages (absence of full yuck in the targeted URL)

I haven't checked whether other mines with expression are behaving similarly or not.

**Comment by sammyjava** [comment]
Check out the new barchart displayer, now colors based on rep group (and sorts by rep group, name). Haven't done anything to the heat map yet.

**Comment by sammyjava** [comment]
Genes are linked correctly on heat map in current version.
