### ISSUE TITLE
PhaseolusMine (and probably other) keyword search broken

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/mine-issues#99]
As per @adf-ncgr "And while I'm mentioning that Mine, I'll note that keyword search currently seems to be broken there:
https://mines.legumeinfo.org/phaseolusmine/keywordSearchResults.do?searchTerm=photosynthesis&searchSubmit=search"

There was a prod-solr host resolving issue I hit a while ago, could be that, but I'll fix it.

**Comment by sammyjava** [comment]
Oh, DOH, I still had "beanmine" in the mine config for the solr context (or whatever it's called), which I deleted since. I'll check all the mines:
- [x] aeschynomenemine
- [x] arachismine
- [x] cajanusmine
- [x] cicermine
- [x] glycinemine
- [x] legumemine
- [x] lensmine
- [x] lupinusmine
- [x] medicagomine
- [x] minimine
- [x] phaseolusmine
- [x] vignamine

**Comment by adf-ncgr** [comment]
great, thanks for fixing so quickly (or at least figuring out the fix)

**Comment by sammyjava** [comment]
Fixed.
